-- liquibase formatted sql
-- changeset MGubina:1
CREATE TABLE coffee_machines
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_on           BOOLEAN NOT NULL,
    amount_water    INTEGER NOT NULL CHECK (amount_water >= 0),
    amount_coffee   INTEGER NOT NULL CHECK (amount_coffee >= 0),
    amount_milk     INTEGER NOT NULL CHECK (amount_milk >= 0),
    amount_sugar    INTEGER NOT NULL CHECK (amount_sugar >= 0)
);
CREATE TABLE coffee_records
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(255) NOT NULL,
    sugar       VARCHAR(255) NOT NULL,
    date_time   TIMESTAMP NOT NULL,
    is_done     BOOLEAN NOT NULL,
    machine_id  BIGINT REFERENCES coffee_machines(id)
);

INSERT INTO coffee_machines(is_on,amount_water,amount_coffee,amount_milk,amount_sugar)
VALUES (true,1000,1000,1000,1000);
